### ISSUE TITLE
Storage with name "local" is not set

### ISSUE THREAD

**Issue by cornernote** [servocoder/RichFilemanager-PHP#3]
I added my credentials to `config.s3.php` and I changed the `filemanager.php` to be like this:

```
//$config = [];
$config = require(__DIR__ . '/vendor/servocoder/richfilemanager-php/src/config/config.s3.php');
$s3 = new \RFM\Repository\S3\Storage($config);
```

Apache gives this:

```
[Wed May 31 23:15:49.362731 2017] [:error] [pid 24639] [client 162.158.2.125:26562] PHP Fatal error:  Uncaught exception 'Exception' with message 'Storage with name "local" is not set.' in /.../connectors/php/vendor/servocoder/richfilemanager-php/src/Application.php:90
Stack trace:
#0 /.../connectors/php/vendor/servocoder/richfilemanager-php/src/Api/LocalApi.php(21): RFM\\Application->getStorage('local')
#1 /.../connectors/php/filemanager.php(114): RFM\\Api\\LocalApi->__construct()
#2 {main} thrown in /.../connectors/php/vendor/servocoder/richfilemanager-php/src/Application.php on line 90
```

Have I missed something?

**Comment by servocoder** [comment]
Have you solved your problem?
I have missed your question somehow.

**Comment by cornernote** [comment]
No, the interface loads, but can't see files. Apache spits out a stack
trace (on my original issue report).

Not sure what to try next.

**Comment by servocoder** [comment]
I can see in your stack trace that you use LocalApi class. but have to use AwsS3Api class instead. Similar to this:

```php
$app = new \RFM\Application();

$config = require(__DIR__ . '/vendor/servocoder/richfilemanager-php/src/config/config.s3.php');
$s3 = new \RFM\Repository\S3\Storage($config);
$s3->setRoot('user_folder', true);

$app->setStorage($s3);

$app->api = new RFM\Api\AwsS3Api();

$app->run();
```

**Comment by servocoder** [comment]
Updated the comment above.

**Comment by cornernote** [comment]
Perfect, I was missing this:

```
$app->api = new RFM\Api\AwsS3Api();
```

Thanks so much for your help!
